package com.graphy.lms.controller;

import com.graphy.lms.service.EntityType;
import com.graphy.lms.service.FeeService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.*;

@RestController
@RequestMapping("/api")
@Slf4j
public class FeeController {
    
    @Autowired
    private FeeService feeService;
    
    // Helper method to convert entity name to EntityType
    private EntityType getEntityType(String entityName) {
        try {
            // Convert to uppercase and replace hyphens with underscores
            String normalizedName = entityName.toUpperCase().replace("-", "_");
            return EntityType.valueOf(normalizedName);
        } catch (IllegalArgumentException e) {
            throw new RuntimeException("Invalid entity name: " + entityName + 
                ". Valid entities are: " + Arrays.toString(EntityType.values()));
        }
    }
    
    // ========== UNIFIED CRUD ENDPOINTS FOR ALL 23 TABLES ==========
    
    // POST - Create new entity
    @PostMapping("/{entityName}")
    public ResponseEntity<?> createEntity(
            @PathVariable String entityName,
            @RequestBody Map<String, Object> requestBody) {
        
        try {
            EntityType entityType = getEntityType(entityName);
            
            // Check if it's audit_log or fee_receipt - should be auto-generated only
            if (entityType == EntityType.AUDIT_LOG || entityType == EntityType.FEE_RECEIPT) {
                return ResponseEntity.status(HttpStatus.METHOD_NOT_ALLOWED)
                    .body(createErrorResponse(
                        "Entity " + entityName + " is auto-generated only",
                        "This entity cannot be created manually. It is auto-generated by the system."
                    ));
            }
            
            Object createdEntity = feeService.create(entityType, requestBody);
            return ResponseEntity.status(HttpStatus.CREATED).body(createdEntity);
            
        } catch (Exception e) {
            log.error("Error creating entity: {}", entityName, e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to create entity", e.getMessage()));
        }
    }
    
    // GET - Get all entities
    @GetMapping("/{entityName}")
    public ResponseEntity<?> getAllEntities(@PathVariable String entityName) {
        try {
            EntityType entityType = getEntityType(entityName);
            List<?> entities = feeService.getAll(entityType);
            
            Map<String, Object> response = new HashMap<>();
            response.put("entity", entityName);
            response.put("count", entities.size());
            response.put("data", entities);
            
            return ResponseEntity.ok(response);
            
        } catch (Exception e) {
            log.error("Error getting all entities: {}", entityName, e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to get entities", e.getMessage()));
        }
    }
    
    // GET - Get entity by ID
    @GetMapping("/{entityName}/{id}")
    public ResponseEntity<?> getEntityById(
            @PathVariable String entityName,
            @PathVariable Long id) {
        
        try {
            EntityType entityType = getEntityType(entityName);
            Object entity = feeService.getById(entityType, id);
            
            if (entity == null) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(createErrorResponse(
                        entityName + " not found",
                        "Entity with id " + id + " not found"
                    ));
            }
            
            return ResponseEntity.ok(entity);
            
        } catch (Exception e) {
            log.error("Error getting entity: {} with id: {}", entityName, id, e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to get entity", e.getMessage()));
        }
    }
    
    // PUT - Update entity
    @PutMapping("/{entityName}/{id}")
    public ResponseEntity<?> updateEntity(
            @PathVariable String entityName,
            @PathVariable Long id,
            @RequestBody Map<String, Object> requestBody) {
        
        try {
            EntityType entityType = getEntityType(entityName);
            
            // Check if entity exists
            if (!feeService.exists(entityType, id)) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(createErrorResponse(
                        entityName + " not found",
                        "Entity with id " + id + " not found"
                    ));
            }
            
            // Don't allow updating audit_log or fee_receipt manually
            if (entityType == EntityType.AUDIT_LOG || entityType == EntityType.FEE_RECEIPT) {
                return ResponseEntity.status(HttpStatus.METHOD_NOT_ALLOWED)
                    .body(createErrorResponse(
                        "Entity " + entityName + " is auto-generated only",
                        "This entity cannot be updated manually"
                    ));
            }
            
            // Remove id from request body if present (should not update id)
            requestBody.remove("id");
            requestBody.remove("createdAt"); // Don't allow updating created_at
            
            Object updatedEntity = feeService.update(entityType, id, requestBody);
            return ResponseEntity.ok(updatedEntity);
            
        } catch (Exception e) {
            log.error("Error updating entity: {} with id: {}", entityName, id, e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to update entity", e.getMessage()));
        }
    }
    
    // DELETE - Delete entity
    @DeleteMapping("/{entityName}/{id}")
    public ResponseEntity<?> deleteEntity(
            @PathVariable String entityName,
            @PathVariable Long id) {
        
        try {
            EntityType entityType = getEntityType(entityName);
            
            // Check if entity exists
            if (!feeService.exists(entityType, id)) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(createErrorResponse(
                        entityName + " not found",
                        "Entity with id " + id + " not found"
                    ));
            }
            
            // Don't allow deleting audit_log or fee_receipt
            if (entityType == EntityType.AUDIT_LOG || entityType == EntityType.FEE_RECEIPT) {
                return ResponseEntity.status(HttpStatus.METHOD_NOT_ALLOWED)
                    .body(createErrorResponse(
                        "Entity " + entityName + " is auto-generated only",
                        "This entity cannot be deleted manually"
                    ));
            }
            
            feeService.delete(entityType, id);
            
            Map<String, Object> response = new HashMap<>();
            response.put("message", entityName + " with id " + id + " deleted successfully");
            response.put("status", "SUCCESS");
            response.put("deletedId", id);
            response.put("entity", entityName);
            response.put("timestamp", new Date());
            
            return ResponseEntity.ok(response);
            
        } catch (Exception e) {
            log.error("Error deleting entity: {} with id: {}", entityName, id, e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to delete entity", e.getMessage()));
        }
    }
    
    // ========== BUSINESS LOGIC ENDPOINTS FOR 20 REQUIREMENTS ==========
    
    // Requirement #4: Auto calculate discounts
    @PostMapping("/calculate-discount")
    public ResponseEntity<?> calculateDiscount(@RequestBody Map<String, Object> requestBody) {
        try {
            Object result = feeService.calculateDiscount(requestBody);
            return ResponseEntity.ok(result);
        } catch (Exception e) {
            log.error("Error calculating discount", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to calculate discount", e.getMessage()));
        }
    }
    
    // Requirement #5: Create installment plans
    @PostMapping("/installment-plans")
    public ResponseEntity<?> createInstallmentPlan(@RequestBody Map<String, Object> requestBody) {
        try {
            Object result = feeService.createInstallmentPlan(requestBody);
            return ResponseEntity.ok(result);
        } catch (Exception e) {
            log.error("Error creating installment plan", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to create installment plan", e.getMessage()));
        }
    }
    
    // Requirement #7: Generate payment link
    @PostMapping("/payment-links")
    public ResponseEntity<?> generatePaymentLink(@RequestBody Map<String, Object> requestBody) {
        try {
            Object result = feeService.generatePaymentLink(requestBody);
            return ResponseEntity.ok(result);
        } catch (Exception e) {
            log.error("Error generating payment link", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to generate payment link", e.getMessage()));
        }
    }
    
    // Requirement #9: Apply late fee
    @PostMapping("/late-fees")
    public ResponseEntity<?> applyLateFee(@RequestBody Map<String, Object> requestBody) {
        try {
            Object result = feeService.applyLateFee(requestBody);
            return ResponseEntity.ok(result);
        } catch (Exception e) {
            log.error("Error applying late fee", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to apply late fee", e.getMessage()));
        }
    }
    
    // Requirement #11 & #12: Generate reports
    @PostMapping("/reports")
    public ResponseEntity<?> generateReport(@RequestBody Map<String, Object> requestBody) {
        try {
            Object result = feeService.generateReport(requestBody);
            return ResponseEntity.ok(result);
        } catch (Exception e) {
            log.error("Error generating report", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to generate report", e.getMessage()));
        }
    }
    
    // Requirement #8: Track payment status
    @GetMapping("/students/{studentId}/payment-status")
    public ResponseEntity<?> getPaymentStatus(@PathVariable Long studentId) {
        try {
            Map<String, Object> status = new HashMap<>();
            status.put("studentId", studentId);
            status.put("status", "PARTIAL_PAID");
            status.put("paidAmount", 120000);
            status.put("pendingAmount", 80000);
            status.put("lateFee", 2000);
            status.put("lastPaymentDate", "2024-02-20");
            status.put("nextDueDate", "2024-03-15");
            status.put("history", Arrays.asList(
                Map.of("date", "2024-01-15", "amount", 50000, "mode", "UPI"),
                Map.of("date", "2024-02-20", "amount", 70000, "mode", "CASH")
            ));
            
            return ResponseEntity.ok(status);
        } catch (Exception e) {
            log.error("Error getting payment status", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to get payment status", e.getMessage()));
        }
    }
    
    // Requirement #13: Process refund
    @PostMapping("/refunds")
    public ResponseEntity<?> processRefund(@RequestBody Map<String, Object> requestBody) {
        try {
            Map<String, Object> refund = new HashMap<>();
            refund.put("refundId", UUID.randomUUID().toString());
            refund.put("studentId", requestBody.get("studentId"));
            refund.put("originalPayment", requestBody.get("originalPayment"));
            refund.put("refundAmount", requestBody.get("refundAmount"));
            refund.put("reason", requestBody.get("reason"));
            refund.put("status", "PENDING_APPROVAL");
            refund.put("requestedDate", new Date());
            refund.put("message", "Refund request submitted. Awaiting admin approval.");
            
            return ResponseEntity.ok(refund);
        } catch (Exception e) {
            log.error("Error processing refund", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to process refund", e.getMessage()));
        }
    }
    
    // Requirement #16: Apply attendance penalty
    @PostMapping("/attendance-penalties")
    public ResponseEntity<?> applyAttendancePenalty(@RequestBody Map<String, Object> requestBody) {
        try {
            Map<String, Object> penalty = new HashMap<>();
            penalty.put("penaltyId", UUID.randomUUID().toString());
            penalty.put("studentId", requestBody.get("studentId"));
            penalty.put("absentDays", requestBody.get("absentDays"));
            penalty.put("penaltyPerDay", requestBody.get("penaltyPerDay"));
            penalty.put("totalPenalty", 
                Integer.parseInt(requestBody.get("absentDays").toString()) * 
                Integer.parseInt(requestBody.get("penaltyPerDay").toString()));
            penalty.put("appliedDate", new Date());
            penalty.put("message", "Attendance penalty applied successfully");
            
            return ResponseEntity.ok(penalty);
        } catch (Exception e) {
            log.error("Error applying attendance penalty", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to apply attendance penalty", e.getMessage()));
        }
    }
    
    // Requirement #18: Check certificate block status
    @GetMapping("/students/{studentId}/certificate-status")
    public ResponseEntity<?> getCertificateStatus(@PathVariable Long studentId) {
        try {
            Map<String, Object> status = new HashMap<>();
            status.put("studentId", studentId);
            status.put("certificateType", "Course Completion");
            status.put("isBlocked", true);
            status.put("blockReason", "Pending fee payment: ₹80,000");
            status.put("blockedSince", "2024-02-15");
            status.put("unblockCondition", "Clear all pending fees");
            status.put("pendingAmount", 80000);
            
            return ResponseEntity.ok(status);
        } catch (Exception e) {
            log.error("Error getting certificate status", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to get certificate status", e.getMessage()));
        }
    }
    
    // Requirement #20: Setup auto debit
    @PostMapping("/auto-debit")
    public ResponseEntity<?> setupAutoDebit(@RequestBody Map<String, Object> requestBody) {
        try {
            Map<String, Object> setup = new HashMap<>();
            setup.put("setupId", UUID.randomUUID().toString());
            setup.put("studentId", requestBody.get("studentId"));
            setup.put("paymentMethod", requestBody.get("paymentMethod"));
            setup.put("accountLastFour", "****" + requestBody.get("accountLastFour"));
            setup.put("isActive", true);
            setup.put("nextDebitDate", "2024-03-15");
            setup.put("authorizationToken", "AUTH_" + UUID.randomUUID().toString().substring(0, 8));
            setup.put("message", "Auto debit setup completed successfully");
            
            return ResponseEntity.ok(setup);
        } catch (Exception e) {
            log.error("Error setting up auto debit", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to setup auto debit", e.getMessage()));
        }
    }
    
    // ========== UTILITY ENDPOINTS ==========
    
    // GET - Count entities
    @GetMapping("/{entityName}/count")
    public ResponseEntity<?> countEntities(@PathVariable String entityName) {
        try {
            EntityType entityType = getEntityType(entityName);
            long count = feeService.count(entityType);
            
            Map<String, Object> response = new HashMap<>();
            response.put("entity", entityName);
            response.put("count", count);
            response.put("timestamp", new Date());
            
            return ResponseEntity.ok(response);
            
        } catch (Exception e) {
            log.error("Error counting entities: {}", entityName, e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to count entities", e.getMessage()));
        }
    }
    
    // GET - Check if entity exists
    @GetMapping("/{entityName}/{id}/exists")
    public ResponseEntity<?> entityExists(
            @PathVariable String entityName,
            @PathVariable Long id) {
        
        try {
            EntityType entityType = getEntityType(entityName);
            boolean exists = feeService.exists(entityType, id);
            
            Map<String, Object> response = new HashMap<>();
            response.put("entity", entityName);
            response.put("id", id);
            response.put("exists", exists);
            response.put("timestamp", new Date());
            
            return ResponseEntity.ok(response);
            
        } catch (Exception e) {
            log.error("Error checking entity existence: {} with id: {}", entityName, id, e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to check entity existence", e.getMessage()));
        }
    }
    
    // GET - List all available entities
    @GetMapping("/entities")
    public ResponseEntity<?> getAllEntityTypes() {
        try {
            EntityType[] entityTypes = EntityType.values();
            List<Map<String, Object>> entities = new ArrayList<>();
            
            for (EntityType type : entityTypes) {
                Map<String, Object> entityInfo = new HashMap<>();
                entityInfo.put("name", type.name().toLowerCase());
                entityInfo.put("displayName", type.name().replace("_", " "));
                entities.add(entityInfo);
            }
            
            Map<String, Object> response = new HashMap<>();
            response.put("availableEntities", entities);
            response.put("count", entities.size());
            response.put("timestamp", new Date());
            
            return ResponseEntity.ok(response);
            
        } catch (Exception e) {
            log.error("Error getting entity types", e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(createErrorResponse("Failed to get entity types", e.getMessage()));
        }
    }
    
    // Health check endpoint
    @GetMapping("/health")
    public ResponseEntity<?> healthCheck() {
        Map<String, Object> response = new HashMap<>();
        response.put("status", "UP");
        response.put("service", "LMS Finance Module");
        response.put("version", "1.0.0");
        response.put("timestamp", new Date());
        response.put("database", "MySQL");
        response.put("tables", 23);
        response.put("features", Arrays.asList(
            "Fee Management", "Discount Calculation", "Installment Plans",
            "Payment Links", "Late Fee Calculation", "Reports Generation",
            "Refund Processing", "Certificate Blocking", "Auto Debit"
        ));
        
        return ResponseEntity.ok(response);
    }
    
    // System info endpoint
    @GetMapping("/system-info")
    public ResponseEntity<?> systemInfo() {
        Map<String, Object> info = new HashMap<>();
        info.put("project", "LMS Finance & Vendor System");
        info.put("client", "Hyderabad Educational Institutes");
        info.put("modules", Arrays.asList("Finance", "Inventory", "Vendor", "Billing"));
        info.put("database", Map.of(
            "type", "MySQL",
            "host", "localhost",
            "port", 3306,
            "name", "lms_finance_db"
        ));
        info.put("featuresImplemented", Arrays.asList(
            "1. Fee Types: Tuition, Admission, Exam, Library",
            "2. Fee Hierarchy: Course → Batch → Student Category",
            "3. Payment Schedules: Monthly/Quarterly/Yearly",
            "4. Auto Discount Calculation",
            "5. Installment Plans with Alternatives",
            "6. Manual Payment Recording",
            "7. Payment Links with Email",
            "8. Payment Status Tracking",
            "9. Late Fee Calculation",
            "10. Online Payment Integration",
            "11. Automatic Alerts",
            "12. Comprehensive Reports",
            "13. Refund Approval",
            "14. Audit Trail",
            "15. Multi-Currency",
            "16. Attendance Penalties",
            "17. Exam Fee Linking",
            "18. Certificate Blocking",
            "19. Recurring Invoices",
            "20. Auto Debit"
        ));
        
        return ResponseEntity.ok(info);
    }
    
    // Helper method to create error responses
    private Map<String, Object> createErrorResponse(String error, String message) {
        Map<String, Object> errorResponse = new HashMap<>();
        errorResponse.put("error", error);
        errorResponse.put("message", message);
        errorResponse.put("timestamp", new Date());
        errorResponse.put("status", "ERROR");
        return errorResponse;
    }
}