package com.graphy.lms.service;

public enum EntityType {
    FEE_TYPE,
    FEE_STRUCTURE,
    STUDENT_FEE_ALLOCATION,
    PAYMENT_INSTALLMENT,
    STUDENT_FEE_PAYMENT,
    FEE_DISCOUNT,
    FEE_REFUND,
    FEE_RECEIPT,
    AUDIT_LOG,
    CURRENCY_RATE,
    NOTIFICATION_LOG,
    ATTENDANCE_PENALTY,
    CERTIFICATE_BLOCK,
    AUTO_DEBIT_SETTING,
    FEE_REPORT,
    INSTALLMENT_PLAN_TEMPLATE,
    PAYMENT_LINK,
    LATE_FEE_RULE,
    EXAM_FEE_MAPPING,
    INVOICE_TEMPLATE,
    AUTO_DEBIT_TRANSACTION,
    ATTENDANCE_PENALTY_RULE,
    REFUND_APPROVAL
}